#!/bin/bash
# Run yabridge test harness with isolated wine + yabridge
set -euo pipefail
ROOT="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
HARNESS="$ROOT/test-harness"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'EOF'
Usage: ./test.sh <yabridge-test-args>

Runs the staging-installed yabridge-test CLI with env.sh loaded.

  ./test.sh info
  ./test.sh probe
  ./test.sh suite

EOF
    exit 0
fi

if [[ ! -f "$ROOT/env.sh" ]]; then
    echo "error: environment is not configured; run ./setup.sh first" >&2
    exit 1
fi
if [[ ! -x "$HARNESS/.venv/bin/yabridge-test" ]]; then
    echo "error: test harness is not installed; run ./setup.sh first" >&2
    exit 1
fi
# env.sh is generated by setup and is not present at lint time.
# shellcheck source=/dev/null
source "$ROOT/env.sh" >&2   # banner to stderr so --dry-run stdout stays pure JSON
exec "$HARNESS/.venv/bin/yabridge-test" "$@"
